### ISSUE TITLE
Skip some views to send to statsd

### ISSUE THREAD

**Issue by patoroco** [WoLpH/django-statsd#14]
Hi,

what do you think about to add a new setting with wildcards for those views that you want to track instead of just to track everything with the middleware?

The use case is avoid to send data about django admin for example.

**Comment by WoLpH** [comment]
In most cases I would argue that it's better to filter it at the graphing side for a few reasons:

1. Since they would get very little requests they would normally not really impact your numbers too much anyhow
2. If they do impact the numbers, they are probably quite significant and possibly useful to see

Having that said, it wouldn't be all that hard to implement but there are 2 ways of going about it I guess.

1. An include/exclude filter by url so we can stop processing very early in the process.
2. Filter by view name at the end of the process. The result is that it won't filter in all cases, if there's an exception that causes the view name not to be available it will still go through.

Would the filter by url be sufficient for you?

**Comment by WoLpH** [comment]
Ping @patoroco  :)

**Comment by patoroco** [comment]
Hi, as I'm using a SaaS for the metrics with a really small plan (I have only 500 allowed metrics), for me it should be better to avoid to send some metrics (i.e. metrics related with django-admin). On this way, I'll continue taking advance on use your `django-statsd` library, but without penalize the number of metrics sent
