### ISSUE TITLE
Unable to stop tracking process_response, never started tracking it

### ISSUE THREAD

**Issue by sudhir-docon** [wolph/django-statsd#21]
When response is returned from middleware, we are getting following error.

```
STATSD_TRACK_MIDDLEWARE = True
```

```Traceback (most recent call last):
  File "~/.virtualenvs/doconpy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "~/.virtualenvs/doconpy/lib/python3.6/site-packages/django/utils/deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "~/.virtualenvs/doconpy/lib/python3.6/site-packages/django_statsd/middleware.py", line 198, in process_response
    StatsdMiddleware.scope.timings.stop('process_response')
  File "~/.virtualenvs/doconpy/lib/python3.6/site-packages/django_statsd/middleware.py", line 103, in stop
    'started tracking it' % key)
AssertionError: Unable to stop tracking process_response, never started tracking it
```

**Comment by WoLpH** [comment]
My guess is that you forgot to add one of the middlewares. Make sure to include both:

2. ``django_statsd.middleware.StatsdMiddleware`` to the **top** of your
    ``MIDDLEWARE``
3. ``django_statsd.middleware.StatsdMiddlewareTimer`` to the **bottom** of your
    ``MIDDLEWARE``

**Comment by sudhir-docon** [comment]
@WoLpH these configs are set properly. It works mostly for all other API requests. 

Only when we have response returned from exception handlers, it throws above error.

**Comment by WoLpH** [comment]
Looking at the Django documentation I think it might be related to a difference between the `MIDDLEWARE` and `MIDDLEWARE_CLASSES` settings of Django. There are a few subtle differences between those.

Still though, if you're getting an uncaught exception I would expect you to end up at `process_exception` instead of `process_response`. But even if you're getting an exception somewhere, if the `StatsdMiddleware` is the **first** of your middlewares, it should still call the `process_response I think. Looking at this documentation: https://docs.djangoproject.com/en/3.1/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

In any case, I think the old middleware style has been supported long enough so I think it can be dropped now so I'll add that to the todo :)

**Comment by jws** [comment]
@sudhir-docon were you able to work around this?

**Comment by WoLpH** [comment]
@jws I've just pushed an update to the develop branch, can you test if that works for you?
If not, can you tell me how to reproduce the issue?

**Comment by danielhusar** [comment]
I'm having a smiliar issue.

This middleware will right now always fail for options calls with`'Access-Control-Request-Method: GET'` header`.

I think the issue is, django will not execute `process_response` hook for those calls, as there is no response for options.
So start timing is never set. But then the `django-statsd` throws error, because it cannot find the start metric.

Heres the curl call you can test this on: `curl -I 'any-api-url' -X OPTIONS -H 'Access-Control-Request-Method: GET'`

**Comment by WoLpH** [comment]
@danielhusar did you try with the develop branch? or the latest release?

I can't seem to reproduce the issue:
```
# curl -I 'localhost:8000/test_app/' -X OPTIONS -H 'Access-Control-Request-Method: GET'
HTTP/1.1 200 OK
Date: Fri, 10 Dec 2021 12:43:48 GMT
Server: WSGIServer/0.2 CPython/3.10.0
Content-Type: text/html; charset=utf-8
Content-Length: 10
```
